version: "3"

services:
    app:
        build:
            context: .
            # dockerfile: C:\Users\ARD\Desktop\ac3\dock-api-test\Dockerfile
            dockerfile: kevinard11/dock-api-test/Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - ./app:/app
        command: >
            sh -c "python manage.py runserver 0.0.0.0:8000"
